const R=[{m:2,f:40},{m:4,f:50},{m:6,f:60},{m:8,f:70},{m:10,f:80},{m:12,f:90},{m:15,f:110},{m:20,f:140}],A=["Paniqui","Moncada","Ramos","Gerona","Pura","Anao","Nampicuan"],P=[["Chicken Meal",120,"Foods","🍗"],["Burger Meal",150,"Foods","🍔"],["Grocery Essentials",250,"Grocery","🛒"],["Market Errand",100,"Market","🏪"],["Essential Needs",180,"Essential Needs","📦"],["Medicine Errand",100,"Medicine","💊"]];let cart=[],orders=JSON.parse(localStorage.mhac_orders||"[]"),gps=JSON.parse(localStorage.mhac_gps||"null");const peso=n=>"₱"+(+n).toFixed(2),fee=k=>(R.find(x=>k<=x.m)||{}).f||null,save=()=>localStorage.mhac_orders=JSON.stringify(orders);
function H(t="MHAC DELIVERY",s="Foods • Grocery • Market • Medicine • Essential Needs"){return`<header class=top><div class=brand>${t}</div><div class=sub>${s}</div></header>`}
function row(p,i){return`<div class=item><span>${p[3]} <b>${p[0]}</b><br>${peso(p[1])}</span><button class=btn onclick="add(${i})">ADD</button></div>`}
function home(){app.innerHTML=`<div class=app>${H()}<main class=content><div class=panel>📍 <b>Service Areas</b><div class=small>${A.join(" • ")}</div></div><div class=section>Categories</div><div class=grid>${["Foods","Grocery","Market","Medicine"].map(x=>`<button class=cat onclick="cat('${x}')">${x}</button>`).join("")}</div><div class=section>Popular</div>${P.slice(0,3).map((p,i)=>row(p,i)).join("")}<div class=section>Orders</div><button class=btn onclick="ordersPage()">📦 My Orders</button><div class=section>Management</div><div class=grid><button class="btn light" onclick=admin()>⚙️ Admin</button><button class="btn light" onclick=rider()>🛵 Rider</button></div></main>${cart.length?`<button class=bottom onclick=checkout()>🛒 ${cart.length} item(s) • ${peso(cart.reduce((s,p)=>s+p[1],0))}</button>`:""}</div>`}
function add(i){cart.push(P[i]);home()}
function cat(c){app.innerHTML=`<div class=app>${H(c)}<main class=content><button class=back onclick=home()>← Back</button>${P.map((p,i)=>p[2]==c?row(p,i):"").join("")}</main></div>`}
function gpsBox(){return`<div class=map id=gpsbox>${gps?`📍 GPS found<br>Lat ${gps.lat.toFixed(6)}<br>Lng ${gps.lon.toFixed(6)}<br><span class=small>±${Math.round(gps.acc)} m</span>`:"📍 GPS LOCATION<br><span class=small>Tap the button below.</span>"}</div><button class=btn style="width:100%;margin:8px 0" onclick=getGPS()>📍 USE MY CURRENT LOCATION</button>`}
function getGPS(){if(!navigator.geolocation)return alert("GPS not supported.");gpsbox.innerHTML="📡 Getting location…";navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lon:p.coords.longitude,acc:p.coords.accuracy};localStorage.mhac_gps=JSON.stringify(gps);gpsbox.innerHTML=`📍 GPS found<br>Lat ${gps.lat.toFixed(6)}<br>Lng ${gps.lon.toFixed(6)}<br><span class=small>±${Math.round(gps.acc)} m</span>`},()=>gpsbox.innerHTML="❌ Location unavailable. Enable phone Location and browser permission.",{enableHighAccuracy:true,timeout:15000})}
function checkout(){app.innerHTML=`<div class=app>${H("CHECKOUT")}<main class=content><button class=back onclick=home()>← Back</button><label>📍 Delivery address</label><input id=addr class=input placeholder="Example: Paniqui, Tarlac">${gpsBox()}<label>🛣️ Road distance (km) — DRY RUN</label><input id=km class=input type=number value=2 min=0 step=.1 oninput=summary()><div class=notice>Production billing must use a secure routing backend to calculate verified road distance from GPS.</div><div id=sum></div><label>Payment</label><select id=pay><option>Cash on Delivery</option><option>GCash</option></select><button class="btn red" style="width:100%" onclick=place()>CONFIRM ORDER</button></main></div>`;summary()}
function summary(){let s=cart.reduce((a,p)=>a+p[1],0),sf=s*.1,k=+(document.querySelector("#km")?.value||0),d=fee(k);sum.innerHTML=`<div class=section>Order Summary</div>${cart.map(p=>`<div class=item><span>${p[3]} ${p[0]}</span><b>${peso(p[1])}</b></div>`).join("")}<div class=item><span>Subtotal</span><b>${peso(s)}</b></div><div class=item><span>Service Fee 10%</span><b>${peso(sf)}</b></div><div class=item><span>Delivery Fee</span><b>${d?peso(d):"Admin approval"}</b></div><p class=total>TOTAL: ${d?peso(s+sf+d):"Admin approval"}</p>`}
function place(){let a=addr.value.trim(),k=+km.value,d=fee(k);if(!a)return alert("Enter address.");if(!A.some(x=>a.toLowerCase().includes(x.toLowerCase())))return alert("Outside MHAC service area.");if(!d)return alert("20+ km requires admin approval.");let s=cart.reduce((x,p)=>x+p[1],0),o={id:"MHAC-"+Date.now(),address:a,km:k,gps,items:cart.map(p=>p[0]),subtotal:s,serviceFee:s*.1,deliveryFee:d,total:s*1.1+d,payment:pay.value,status:"NEW",rider:"Unassigned",created:new Date().toLocaleString()};orders.unshift(o);save();cart=[];alert("Order received: "+o.id);ordersPage()}
function ordersPage(){app.innerHTML=`<div class=app>${H("MY ORDERS")}<main class=content><button class=back onclick=home()>← Back</button>${orders.length?orders.map(o=>`<div class=panel><b>${o.id}</b> <span class=badge>${o.status}</span><div class=small>${o.created}</div><p>📍 ${o.address}</p><p>💰 ${peso(o.total)} • ${o.payment}</p><p>🛵 ${o.rider}</p></div>`).join(""):"<p>No orders yet.</p>"}</main></div>`}
function admin(){app.innerHTML=`<div class=app>${H("MHAC ADMIN","Orders • Riders • Rates")}<main class=content><button class=back onclick=home()>← Back</button><div class=notice>Prototype admin. Production needs secure authentication/backend.</div><div class=section>Orders</div>${orders.map(o=>`<div class=panel><b>${o.id}</b> <span class=badge>${o.status}</span><div>${o.address} • ${peso(o.total)}</div><select class=input onchange="st('${o.id}',this.value)">${["NEW","ACCEPTED","PREPARING","RIDER ASSIGNED","OUT FOR DELIVERY","DELIVERED","CANCELLED"].map(s=>`<option ${s==o.status?"selected":""}>${s}</option>`).join("")}</select><select class=input onchange="ar('${o.id}',this.value)">${["Unassigned","Rider 1","Rider 2"].map(r=>`<option ${r==o.rider?"selected":""}>${r}</option>`).join("")}</select></div>`).join("")||"<p>No orders.</p>"}<div class=section>Delivery Rates</div>${R.map(x=>`<div class=item><span>Up to ${x.m} km</span><b>${peso(x.f)}</b></div>`).join("")}</main></div>`}
function st(id,s){let o=orders.find(x=>x.id==id);if(o)o.status=s;save();admin()}function ar(id,r){let o=orders.find(x=>x.id==id);if(o)o.rider=r;save();admin()}
function rider(){app.innerHTML=`<div class=app>${H("RIDER","Delivery dashboard")}<main class=content><button class=back onclick=home()>← Back</button><div class=panel><b>Rider 1</b> <span class="badge ok">ONLINE</span>${gpsBox()}</div><div class=section>Assigned Deliveries</div>${orders.filter(o=>o.rider=="Rider 1").map(o=>`<div class=panel><b>${o.id}</b><p>📍 ${o.address}</p><p>${peso(o.total)}</p><button class="btn red" onclick="st('${o.id}','OUT FOR DELIVERY')">START DELIVERY</button></div>`).join("")||"<p>No assigned deliveries.</p>"}</main></div>`}
home();