const R=[{m:2,f:40},{m:4,f:50},{m:6,f:60},{m:8,f:70},{m:10,f:80},{m:12,f:90},{m:15,f:110},{m:20,f:140}];
const A=["Paniqui","Moncada","Ramos","Gerona","Pura","Anao","Nampicuan"];
const P=[["Chicken Meal",120,"Foods","🍗"],["Burger Meal",150,"Foods","🍔"],["Grocery Essentials",250,"Grocery","🛒"],["Market Errand",100,"Market","🏪"],["Essential Needs",180,"Essential Needs","📦"],["Medicine Errand",100,"Medicine","💊"]];
let cart=JSON.parse(localStorage.mhac_cart||"[]"),orders=JSON.parse(localStorage.mhac_orders||"[]"),gps=JSON.parse(localStorage.mhac_gps||"null");
const peso=n=>"₱"+Number(n||0).toFixed(2);
const save=()=>{localStorage.mhac_cart=JSON.stringify(cart);localStorage.mhac_orders=JSON.stringify(orders);if(gps)localStorage.mhac_gps=JSON.stringify(gps)};
function H(t="MHAC DELIVERY",s="Foods • Grocery • Market • Medicine • Essential Needs"){return `<header class="top"><div class="brand">${t}</div><div class="sub">${s}</div></header>`}
function row(p,i){return `<div class="item"><span>${p[3]} <b>${p[0]}</b><br>${peso(p[1])}</span><button class="btn" onclick="add(${i})">ADD</button></div>`}
function home(){app.innerHTML=`<div class="app">${H()}<main class="content"><div class="panel"><b>📍 Service Areas</b><div class="small">${A.join(" • ")}</div></div><div class="section">Categories</div><div class="grid">${["Foods","Grocery","Market","Medicine"].map(x=>`<button class="cat" onclick="cat('${x}')">${x}</button>`).join("")}</div><div class="section">Popular</div>${P.slice(0,3).map((p,i)=>row(p,i)).join("")}<div class="section">Orders</div><button class="btn" onclick="ordersPage()">📦 My Orders</button><div class="section">Management</div><div class="grid"><button class="btn light" onclick="admin()">⚙️ Admin</button><button class="btn light" onclick="rider()">🛵 Rider</button></div>${cart.length?`<button class="bottom" onclick="checkout()">🛒 ${cart.length} item(s) • ${peso(cart.reduce((s,p)=>s+p[1],0))}</button>`:""}</main></div>`}
function add(i){cart.push(P[i]);save();home()}
function cat(c){let list=P.filter(p=>p[2]===c);app.innerHTML=`<div class="app">${H(c)}<main class="content"><button class="back" onclick="home()">← Back</button><div class="section">${c}</div>${list.length?list.map(p=>row(p,P.indexOf(p))).join(""):`<div class="notice">No products yet.</div>`}</main></div>`}
function deliveryFee(k){k=Number(k||0);if(k<=2)return 40;if(k<=4)return 50;if(k<=6)return 60;if(k<=8)return 70;if(k<=10)return 80;if(k<=12)return 90;if(k<=15)return 110;if(k<=20)return 140;return null}
function getGPS(){let m=document.getElementById("gpsmsg");if(!navigator.geolocation){if(m)m.innerHTML="❌ GPS is not supported.";return}if(m)m.innerHTML="📍 Getting GPS...";navigator.geolocation.getCurrentPosition(p=>{gps={lat:p.coords.latitude,lng:p.coords.longitude};save();if(m)m.innerHTML=`✅ GPS Found<br>Lat: ${gps.lat.toFixed(6)}<br>Lng: ${gps.lng.toFixed(6)}`},()=>{if(m)m.innerHTML="❌ GPS failed. Allow Location permission."},{enableHighAccuracy:true,timeout:10000,maximumAge:0})}
function checkout(){if(!cart.length){alert("Walang laman ang cart.");return home()}let sub=cart.reduce((s,p)=>s+p[1],0),sf=sub*.1;app.innerHTML=`<div class="app">${H("CHECKOUT","Review your order before placing it")}<main class="content"><button class="back" onclick="home()">← Back</button><div class="panel"><div class="section">Customer Information</div><label>Full Name</label><input id="cname" placeholder="Enter your full name"><label>Mobile Number</label><input id="cphone" type="tel" placeholder="09XXXXXXXXX"><label>Complete Delivery Address</label><input id="caddress" placeholder="House / Street / Barangay / Municipality"><label>Delivery Area</label><select id="carea">${A.map(x=>`<option>${x}</option>`).join("")}</select><label>Distance (KM)</label><input id="cdistance" type="number" min="0" step="0.1" placeholder="Enter distance in KM"><button class="btn light" onclick="getGPS()">📍 Use My GPS Location</button><div id="gpsmsg" class="notice">${gps?"GPS already saved.":"GPS location not yet selected."}</div></div><div class="panel"><div class="section">Order Summary</div>${cart.map((p,i)=>`<div class="item"><span>${p[3]} <b>${p[0]}</b><br>${peso(p[1])}</span><button class="btn red" onclick="removeCart(${i})">REMOVE</button></div>`).join("")}<div class="item"><span>Subtotal</span><b>${peso(sub)}</b></div><div class="item"><span>10% Service Fee</span><b>${peso(sf)}</b></div><div id="deliveryPreview" class="item"><span>Delivery Fee</span><b>Enter distance</b></div><div id="totalPreview" class="total">TOTAL: ${peso(sub+sf)}</div></div><div class="panel"><div class="section">Payment Method</div><label><input type="radio" name="payment" value="COD" checked> 💵 Cash on Delivery</label><label><input type="radio" name="payment" value="GCASH"> 📱 GCash Payment</label><div class="notice">For GCash, screenshot/proof of payment may be required.</div></div><button class="bottom" onclick="placeOrder()">🛵 PLACE ORDER</button></main></div>`;document.getElementById("cdistance").oninput=()=>{let k=Number(cdistance.value||0),df=deliveryFee(k);deliveryPreview.innerHTML=`<span>Delivery Fee</span><b>${df===null?"Admin approval":peso(df)}</b>`;totalPreview.innerHTML=`TOTAL: ${df===null?"Admin approval":peso(sub+sf+df)}`}}
function removeCart(i){cart.splice(i,1);save();checkout()}
function placeOrder(){let name=cname.value.trim(),phone=cphone.value.trim(),address=caddress.value.trim(),area=carea.value,k=Number(cdistance.value||0),payment=document.querySelector('input[name="payment"]:checked')?.value||"COD";if(!name)return alert("Ilagay ang pangalan.");if(!phone)return alert("Ilagay ang mobile number.");if(!address)return alert("Ilagay ang complete delivery address.");if(!k||k<0)return alert("Ilagay ang delivery distance.");let df=deliveryFee(k);if(df===null)return alert("20KM pataas. Kailangan muna ng admin approval.");let sub=cart.reduce((s,p)=>s+p[1],0),sf=sub*.1,o={id:"MHAC-"+Date.now().toString().slice(-8),date:new Date().toLocaleString(),customer:name,phone,address,area,distance:k,gps:gps||null,payment,items:cart.map(p=>({name:p[0],price:p[1],category:p[2],icon:p[3]})),subtotal:sub,serviceFee:sf,deliveryFee:df,total:sub+sf+df,status:"PENDING",rider:null};orders.unshift(o);cart=[];save();app.innerHTML=`<div class="app">${H("ORDER CONFIRMED","Thank you for using MHAC DELIVERY")}<main class="content"><div class="panel"><div class="section">✅ Order Successfully Placed</div><div class="notice ok">Your order has been received.</div><div class="item"><span>Order Number</span><b>${o.id}</b></div><div class="item"><span>Customer</span><b>${o.customer}</b></div><div class="item"><span>Payment</span><b>${o.payment}</b></div><div class="item"><span>Status</span><b class="badge">${o.status}</b></div><div class="item"><span>Subtotal</span><b>${peso(o.subtotal)}</b></div><div class="item"><span>10% Service Fee</span><b>${peso(o.serviceFee)}</b></div><div class="item"><span>Delivery Fee</span><b>${peso(o.deliveryFee)}</b></div><div class="total">TOTAL: ${peso(o.total)}</div></div><button class="btn" onclick="ordersPage()">📦 MY ORDERS</button><button class="btn light" onclick="home()">🏠 BACK TO HOME</button></main></div>`}
function ordersPage(){app.innerHTML=`<div class="app">${H("MY ORDERS","Track your MHAC DELIVERY orders")}<main class="content"><button class="back" onclick="home()">← Back</button><div class="section">Order History</div>${orders.length?orders.map(o=>`<div class="panel"><div class="item"><span><b>${o.id}</b><br>${o.date}</span><b class="badge">${o.status}</b></div><div class="small">${o.customer} • ${o.area}</div><div class="small">${o.items.map(x=>x.name).join(", ")}</div><div class="item"><span>Total</span><b>${peso(o.total)}</b></div>${o.rider?`<div class="notice">🛵 Rider: ${o.rider}</div>`:""}</div>`).join(""):`<div class="notice">No orders yet.</div>`}</main></div>`}
function admin(){app.innerHTML=`<div class="app">${H("ADMIN","Order management")}<main class="content"><button class="back" onclick="home()">← Back</button><div class="section">Orders</div>${orders.length?orders.map((o,i)=>`<div class="panel"><div class="item"><span><b>${o.id}</b><br>${o.customer}<br>${o.phone}</span><b>${peso(o.total)}</b></div><div class="small">${o.address} • ${o.area} • ${o.distance} KM</div><div class="small">Payment: ${o.payment}</div><label>Status</label><select onchange="setStatus(${i},this.value)">${["PENDING","ACCEPTED","PREPARING","OUT FOR DELIVERY","DELIVERED","CANCELLED"].map(s=>`<option ${o.status===s?"selected":""}>${s}</option>`).join("")}</select><label>Assign Rider</label><input value="${o.rider||""}" placeholder="Rider name" onchange="setRider(${i},this.value)"></div>`).join(""):`<div class="notice">No orders.</div>`}</main></div>`}
function setStatus(i,v){if(orders[i]){orders[i].status=v;save();admin()}}
function setRider(i,v){if(orders[i]){orders[i].rider=v.trim()||null;save()}}
function rider(){let a=orders.filter(o=>["ACCEPTED","PREPARING","OUT FOR DELIVERY"].includes(o.status));app.innerHTML=`<div class="app">${H("RIDER","Delivery dashboard")}<main class="content"><button class="back" onclick="home()">← Back</button><div class="section">Assigned Orders</div>${a.length?a.map(o=>`<div class="panel"><div class="item"><span><b>${o.id}</b><br>${o.customer}</span><b>${peso(o.total)}</b></div><div class="small">📍 ${o.address}</div><div class="small">📞 ${o.phone}</div><button class="btn" onclick="riderDeliver('${o.id}')">✅ Mark Delivered</button></div>`).join(""):`<div class="notice">No active deliveries.</div>`}</main></div>`}
function riderDeliver(id){let o=orders.find(x=>x.id===id);if(o){o.status="DELIVERED";save()}rider()}
home();